[package]
name = "golden-tests"
version = "0.2.0"
authors = ["Jake Fecher <jfecher11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
difference = "2.0.0"
